name: Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  docs:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Node toolchain
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-docs
        with:
          path: ~/.npm
          key: ${{ runner.os }}-docs-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-docs-${{ env.cache-name }}-
            ${{ runner.os }}-docs-
            ${{ runner.os }}-

      # install, build, test
      - name: Install dependencies
        run: yarn
      - name: Build documentation
        run: yarn build
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist